server:
  port: 8086

spring:
  application:
    name: wallet-service
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:${DB_HOST:localhost}}:${POSTGRES_PORT:${DB_PORT:5432}}/${POSTGRES_DB:${DB_NAME:kado24_db}}?currentSchema=wallet_schema
    username: ${POSTGRES_USER:${DB_USER:kado24_user}}
    password: ${POSTGRES_PASSWORD:${DB_PASSWORD:kado24_pass}}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 3
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:kado24_redis_pass}
      timeout: 60000ms
  
  # Kafka configuration (commented out - Kafka removed from infrastructure)
  # kafka:
  #   bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}

jwt:
  secret: kado24-secret-key-change-this-in-production-minimum-256-bits-required-for-security

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus

logging:
  level:
    com.kado24: INFO
    com.kado24.wallet: INFO
    com.kado24.wallet.service: INFO
    com.kado24.wallet.service.ExternalServiceClient: DEBUG

internal:
  api:
    secret: ${INTERNAL_SERVICE_SECRET:kado24-internal-secret}

services:
  voucher:
    url: ${VOUCHER_SERVICE_URL:http://kado24-voucher-service:8083}
  merchant:
    url: ${MERCHANT_SERVICE_URL:http://kado24-merchant-service:8088}

springdoc:
  swagger-ui:
    path: /swagger-ui.html











